branch-defaults:
  master:
    environment: Udagramapi-env
environment-defaults:
  Udagramapi-env:
    branch: master
    repository: udagram-Project3
global:
  application_name: udagram-api
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
