Deploy:
  artifact: www/Arcive.zip
branch-defaults:
  default:
    environment: Udagramapi-env
    group_suffix: null
environment-defaults:
  Udagramapi-env:
    branch: null
    repository: null
global:
  application_name: udagram-api
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
